controllers:

  local:

    available:

      osken:

        class: engine.controllers.plugins.osken.controller.OsKenController


      ryu:

        class: engine.controllers.plugins.ryu.controller.RyuController


  remote:

    available:

      onos:

        type: remote

        ip: 127.0.0.1

        port: 6653


      floodlight:

        type: remote

        ip: 127.0.0.1

        port: 6653


      opendaylight:

        type: remote

        ip: 127.0.0.1

        port: 6653
